API_TITLE: BUTTON SERVER API
API_VERSION: v1

# openapi.json version and URL prefix
OPENAPI_VERSION: 3.0.3
OPENAPI_URL_PREFIX: /

# Enable swagger UI
OPENAPI_SWAGGER_UI_PATH: /docs
OPENAPI_SWAGGER_UI_URL: https://cdn.jsdelivr.net/npm/swagger-ui-dist/

# Thread configuration
THREAD_SERIAL_INTERFACE: /dev/ttyACM0
THREAD_SERIAL_SPEED: 115200
THREAD_UDP_PORT: 45
THREAD_MESSAGES: server_button/server/config/thread-messages.yml
THREAD_IPV6_MESH: fe80:0:0:0:bc69:1e17:102c:5655
THREAD_DATSET_KEY: 0e080000000000010000000300000e35060004001fffe002084dbae37e3b1de4ee0708fd742fe48d5a1317051000112233445566778899aabbccddeeff030f4f70656e5468726561642d3465353601024e56041042ea7b8f55878049c237bfaf6cf0ff2b0c0402a0f7f8

# Peripherals configuration
PERIPHERALS_BUTTON: 21
WIFI_CONNECTION_STATUS_POLL_PERIOD_IN_SECS: 1

# RPI BOX SERVER CONFIGURATION
RPI_BOX_IP: 192.168.1.23
RPI_BOX_PORT: 5000
RPI_BOX_THREAD_PATH: thread/setup

# PiJuice battery configuration
PIJUICE_BAT_POLLING_PERIOD_IN_MINS: 1
PIJUICE_LOW_BAT_THRESHOLD_IN_PERCENTAGE: 5
PIJUICE_DEVICE_ID: 1
